heartbeat.monitors:
  - type: http
    id: kibana-monitor
    name: kibana-monitor
    schedule: "@every 30s"
    timeout: 30s
    urls:
      - http://kibana:5601

  - type: http
    id: python-monitor
    name: python-monitor
    schedule: "@every 30s"
    timeout: 30s
    urls:
      - http://python-app:5000

  - type: http
    id: java-monitor
    name: java-monitor
    schedule: "@every 30s"
    timeout: 30s
    urls:
      - http://java-app:8080

  - type: http
    id: go-monitor
    name: go-monitor
    schedule: "@every 30s"
    timeout: 30s
    urls:
      - http://go-app:8080

  - type: icmp
    id: icmp-elk
    name: icmp-elk
    schedule: "@every 5s"
    hosts:
      - elasticsearch
      - kibana

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "http://kibana:5601"
