heartbeat.monitors:
  - type: http
    id: kibana-monitor
    name: kibana-monitor
    schedule: "@every 30s"
    timeout: 30s
    urls:
      - http://kibana:5601

  - type: http
    id: python-monitor
    name: python-monitor
    schedule: "@every 30s"
    timeout: 30s
    urls:
      - http://python-app:5000

  - type: http
    id: java-monitor
    name: java-monitor
    schedule: "@every 30s"
    timeout: 30s
    urls:
      - http://java-app:8080

  - type: http
    id: go-monitor
    name: go-monitor
    schedule: "@every 30s"
    timeout: 30s
    urls:
      - http://go-app:8080

  - type: http
    id: nginx-php-monitor
    name: nginx-php-monitor
    schedule: "@every 30s"
    timeout: 30s
    urls:
      - http://nginx:80

  - type: icmp
    id: icmp-elk
    name: icmp-elk
    schedule: "@every 5s"
    hosts:
      - elasticsearch
      - kibana

output.elasticsearch:
  hosts: ["https://elasticsearch:9200"]
  username: "elastic"
  password: "changeme"
  ssl:
    certificate_authorities: ['elasticsearch-ca.pem']

setup.kibana:
  host: "https://kibana:5601"

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/metricbeat/current/http-endpoint.html
#

http.enabled: true
http.host: 0.0.0.0
