version: "3.2"

services:

  traefik:
    image: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - elk
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
      # (!) TLS certificates. Generate using instructions from tls/README.md.
      - type: bind
        source: ./tls/elasticsearch/elasticsearch.p12
        target: /usr/share/elasticsearch/config/elasticsearch.p12
        read_only: true
      - type: bind
        source: ./tls/elasticsearch/http.p12
        target: /usr/share/elasticsearch/config/http.p12
        read_only: true
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.elasticsearch.rule=Host(`elasticsearch.localhost`)"

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      # (!) CA certificate. Generate using instructions from tls/README.md
      - type: bind
        source: ./tls/kibana/elasticsearch-ca.pem
        target: /usr/share/logstash/config/elasticsearch-ca.pem
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.logstash.rule=Host(`logstash.localhost`)"

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
      # (!) CA certificate. Generate using instructions from tls/README.md.
      - type: bind
        source: ./tls/kibana/elasticsearch-ca.pem
        target: /usr/share/kibana/config/elasticsearch-ca.pem
        read_only: true
    networks:
      - elk
    depends_on:
      - elasticsearch
    labels: 
      - "traefik.enable=true"           
      - "traefik.http.routers.kibana.rule=Host(`kibana.localhost`)"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"

  apm-server:
    build:
      context: apm-server/
      args:
        ELK_VERSION: $ELK_VERSION
    command:
      # Disable strict permission checking on 'apm-server.yml' configuration file
      # https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html
      - --strict.perms=false
    volumes:
      - type: bind
        source: ./apm-server/config/apm-server.yml
        target: /usr/share/apm-server/apm-server.yml
        read_only: true
      # (!) CA certificate. Generate using instructions from tls/README.md
      - type: bind
        source: ./tls/kibana/elasticsearch-ca.pem
        target: /usr/share/apm-server/elasticsearch-ca.pem
        read_only: true
    ports:
      - "8200:8200"
    networks:
      - elk
    depends_on:
      - elasticsearch
    labels: 
      - "traefik.enable=true"           
      - "traefik.http.routers.apm-server.rule=Host(`apm.localhost`)"

  heartbeat:
    build:
      context: heartbeat/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./heartbeat/config/heartbeat.yml
        target: /usr/share/heartbeat/heartbeat.yml
        read_only: true
      # (!) CA certificate. Generate using instructions from tls/README.md
      - type: bind
        source: ./tls/kibana/elasticsearch-ca.pem
        target: /usr/share/heartbeat/elasticsearch-ca.pem
        read_only: true
    command: heartbeat -e -strict.perms=false
    networks:
      - elk
    depends_on:
      - elasticsearch

  metricbeat:
    build:
      context: metricbeat/
      args:
        ELK_VERSION: $ELK_VERSION
    user: root
    volumes:
      - type: bind
        source: ./metricbeat/config/metricbeat.yml
        target: /usr/share/metricbeat/metricbeat.yml
        read_only: true
       # (!) CA certificate. Generate using instructions from tls/README.md
      - type: bind
        source: ./tls/kibana/elasticsearch-ca.pem
        target: /usr/share/metricbeat/elasticsearch-ca.pem
        read_only: true
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    networks:
      - elk
    depends_on:
      - elasticsearch
    command: metricbeat -e

  filebeat:
    build:
      context: filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    user: root
    volumes:
      - type: bind
        source: ./filebeat/config/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
      # (!) CA certificate. Generate using instructions from tls/README.md
      - type: bind
        source: ./tls/kibana/elasticsearch-ca.pem
        target: /usr/share/filebeat/elasticsearch-ca.pem
        read_only: true
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elk
    depends_on:
      - elasticsearch
    command: filebeat -e -strict.perms=false

  python-app:
    build: apps/python-app
    volumes:
      - ./apps/python-app:/usr/src/app
    networks:
      - elk    
    labels: 
      - "traefik.enable=true"           
      - "traefik.http.routers.python-app.rule=Host(`python.localhost`)"
      - "traefik.http.services.python-app.loadbalancer.server.port=5000"

  java-app:
    build: apps/java-app
    networks:
      - elk
    labels: 
      - "traefik.enable=true"           
      - "traefik.http.routers.java-app.rule=Host(`java.localhost`)"
      - "traefik.http.services.java-app.loadbalancer.server.port=8080"

  php-app:
    build: 
      context: apps/php-app
      dockerfile: docker/php/Dockerfile
    environment: 
      ELASTIC_APM_SERVER_URL: http://apm-server:8200
      ELASTIC_APM_SERVICE_NAME: PHP App
      ELASTIC_APM_SERVICE_TOKEN: changeme
    volumes:
      - ./apps/php-app:/var/www
    networks:
      - elk

  go-app:
    build: apps/go-app    
    networks:
      - elk
    labels: 
      - "traefik.enable=true"           
      - "traefik.http.routers.go-app.rule=Host(`go.localhost`)"
      - "traefik.http.services.go-app.loadbalancer.server.port=8080"

  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./apps/php-app:/var/www
      - ./apps/php-app/docker/nginx:/etc/nginx/conf.d
    networks:
      - elk
    labels: 
      - "traefik.enable=true"           
      - "traefik.http.routers.nginx.rule=Host(`php.localhost`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}  
    networks:
      - elk

  elastalert:
    build: elastalert
    volumes:
      - ./elastalert:/usr/src/app
    volumes: 
      - type: bind
        source: ./tls/kibana/elasticsearch-ca.pem
        target: /usr/src/app/elasticsearch-ca.pem
        read_only: true
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
